export const WEB_MODE_A_HTML = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="UTF-8">',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '  <title>ISL Bridge - Live Detection</title>',
  '  <style>',
  '    :root {',
  '      --bg: #07070F;',
  '      --panel: #0F0F1E;',
  '      --border: #1A1A3A;',
  '      --text: #E0E0F0;',
  '      --muted: #44446A;',
  '      --accent: #00F5D4;',
  '      --accent-bg: #001A12;',
  '      --danger: #F72585;',
  '      --warn: #FFD166;',
  '    }',
  '    body.light {',
  '      --bg: #F0F4F8;',
  '      --panel: #FFFFFF;',
  '      --border: #DCE3EE;',
  '      --text: #0A0A1A;',
  '      --muted: #5B6480;',
  '      --accent: #008B7A;',
  '      --accent-bg: #E0F5F2;',
  '      --danger: #C2185B;',
  '      --warn: #C98B00;',
  '    }',
  '    * { box-sizing: border-box; margin: 0; padding: 0; }',
  '    body { background: var(--bg); color: var(--text); font-family: "Courier New", monospace; min-height: 100vh; }',
  '    .topbar { display: flex; justify-content: space-between; align-items: center; padding: 14px 20px; background: var(--panel); border-bottom: 1px solid var(--border); }',
  '    .logo { display: flex; align-items: center; gap: 10px; }',
  '    .logo-icon { font-size: 16px; font-weight: bold; color: var(--accent); }',
  '    .logo-name { font-size: 16px; font-weight: bold; color: var(--text); }',
  '    .logo-team { font-size: 10px; color: var(--muted); margin-top: 2px; }',
  '    .topbar-btns { display: flex; gap: 8px; }',
  '    .btn-small { border: 1px solid var(--border); background: var(--panel); color: var(--text); padding: 6px 14px; border-radius: 6px; cursor: pointer; font-family: inherit; font-size: 12px; font-weight: bold; }',
  '    .btn-small.accent { border-color: var(--accent); color: var(--accent); }',
  '    .main { display: grid; grid-template-columns: 1fr 360px; gap: 16px; padding: 16px; max-width: 1100px; margin: 0 auto; min-height: calc(100vh - 60px); }',
  '    .camera-section { display: flex; flex-direction: column; gap: 12px; }',
  '    .camera-wrap { position: relative; background: var(--panel); border: 1px solid var(--border); border-radius: 12px; overflow: hidden; min-height: 420px; }',
  '    #video, #canvas { width: 100%; height: 100%; object-fit: cover; display: block; transform: scaleX(-1); }',
  '    #canvas { position: absolute; inset: 0; }',
  '    .camera-overlay-text { position: absolute; top: 12px; left: 12px; background: rgba(0,0,0,.45); padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: bold; color: var(--accent); }',
  '    .sign-overlay { position: absolute; left: 0; right: 0; bottom: 0; display: none; align-items: flex-end; justify-content: space-between; padding: 20px; background: linear-gradient(transparent, rgba(0,0,0,.65)); }',
  '    .sign-big { font-size: 48px; font-weight: bold; color: #fff; }',
  '    .conf-badge { background: rgba(0,0,0,.4); border: 1px solid var(--accent); color: var(--accent); padding: 4px 10px; border-radius: 4px; font-size: 12px; }',
  '    .controls { display: flex; gap: 10px; }',
  '    .btn-primary { flex: 1; background: var(--accent); color: var(--bg); border: none; padding: 14px; border-radius: 10px; font-size: 14px; font-weight: bold; font-family: inherit; cursor: pointer; }',
  '    .btn-primary.active { background: var(--bg); color: var(--accent); border: 1.5px solid var(--accent); }',
  '    .btn-clear { background: var(--panel); color: var(--muted); border: 1px solid var(--border); padding: 14px 20px; border-radius: 10px; font-size: 13px; font-family: inherit; cursor: pointer; }',
  '    .panel { display: flex; flex-direction: column; gap: 12px; overflow-y: auto; }',
  '    .card { background: var(--panel); border: 1px solid var(--border); border-radius: 12px; padding: 16px; }',
  '    .card-label { font-size: 10px; letter-spacing: .2em; color: var(--muted); text-transform: uppercase; margin-bottom: 12px; }',
  '    .status-row { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }',
  '    .status-dot { width: 8px; height: 8px; border-radius: 50%; }',
  '    .status-text { font-size: 12px; color: var(--text); opacity: .8; }',
  '    .lang-toggle { display: flex; background: rgba(8,8,24,.6); border: 1px solid var(--border); border-radius: 8px; overflow: hidden; }',
  '    .lang-btn { flex: 1; padding: 10px; border: none; background: transparent; color: var(--muted); font-family: inherit; font-size: 12px; font-weight: bold; cursor: pointer; }',
  '    .lang-btn.active { background: rgba(0,245,212,.12); color: var(--accent); }',
  '    .output-sign { font-size: 52px; font-weight: bold; color: var(--text); margin-bottom: 4px; min-height: 64px; }',
  '    .output-hindi { font-size: 18px; color: var(--accent); margin-bottom: 12px; }',
  '    .output-placeholder, .history-empty { font-size: 13px; color: var(--muted); font-style: italic; }',
  '    .output-meta { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 8px; }',
  '    .meta-badge { font-size: 10px; padding: 3px 10px; border-radius: 4px; border: 1px solid rgba(0,245,212,.25); color: var(--accent); }',
  '    .btn-speak { width: 100%; background: var(--accent-bg); border: 1px solid rgba(0,245,212,.25); color: var(--accent); padding: 10px; border-radius: 8px; font-family: inherit; font-size: 13px; cursor: pointer; margin-top: 8px; }',
  '    .history-list { display: flex; flex-direction: column; gap: 6px; max-height: 200px; overflow-y: auto; }',
  '    .history-item { display: flex; justify-content: space-between; align-items: center; padding: 8px 12px; background: rgba(8,8,24,.6); border: 1px solid var(--border); border-radius: 6px; }',
  '    .history-sign { font-size: 14px; font-weight: bold; color: var(--text); }',
  '    .history-conf { font-size: 11px; color: var(--muted); }',
  '    .mode-tab { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 14px; text-align: center; cursor: pointer; font-family: inherit; font-size: 13px; color: var(--muted); width: 100%; }',
  '    @media (max-width: 700px) { .main { grid-template-columns: 1fr; } .camera-wrap { min-height: 300px; } }',
  '  </style>',
  '</head>',
  '<body>',
  '  <div class="topbar">',
  '    <div class="logo">',
  '      <span class="logo-icon">ISL</span>',
  '      <div>',
  '        <div class="logo-name">ISL Bridge</div>',
  '        <div class="logo-team">Team ALPHA - KCCITM</div>',
  '      </div>',
  '    </div>',
  '    <div class="topbar-btns">',
  '      <button class="btn-small" onclick="toggleTheme()" id="themeBtn">Light</button>',
  '      <button class="btn-small accent" onclick="toggleMode()">Mode B</button>',
  '    </div>',
  '  </div>',
  '  <div class="main">',
  '    <div class="camera-section">',
  '      <div class="camera-wrap">',
  '        <video id="video" autoplay playsinline></video>',
  '        <canvas id="canvas"></canvas>',
  '        <div class="camera-overlay-text" id="cameraStatus">Camera loading...</div>',
  '        <div class="sign-overlay" id="signOverlay">',
  '          <div class="sign-big" id="overlaySign">A</div>',
  '          <div class="conf-badge" id="overlayConf">95%</div>',
  '        </div>',
  '      </div>',
  '      <div class="controls">',
  '        <button class="btn-primary" id="startBtn" onclick="toggleDetection()">Start Signing</button>',
  '        <button class="btn-clear" onclick="clearAll()">Clear</button>',
  '      </div>',
  '    </div>',
  '    <div class="panel">',
  '      <div class="card">',
  '        <div class="card-label">System Status</div>',
  '        <div class="status-row"><div class="status-dot" id="camDot" style="background:#FFD166"></div><div class="status-text" id="camStatus">Camera: Loading...</div></div>',
  '        <div class="status-row"><div class="status-dot" id="mpDot" style="background:#FFD166"></div><div class="status-text" id="mpStatus">MediaPipe: Loading...</div></div>',
  '        <div class="status-row"><div class="status-dot" id="aiDot" style="background:#FFD166"></div><div class="status-text" id="aiStatus">AI Model: Connecting...</div></div>',
  '      </div>',
  '      <div class="card">',
  '        <div class="card-label">Language</div>',
  '        <div class="lang-toggle">',
  '          <button class="lang-btn active" id="btnEN" onclick="setLang(\'en\')">English</button>',
  '          <button class="lang-btn" id="btnHI" onclick="setLang(\'hi\')">Hindi</button>',
  '        </div>',
  '      </div>',
  '      <div class="card" id="outputCard">',
  '        <div class="card-label" id="outputLabel">Detected Sign</div>',
  '        <div id="outputArea"><div class="output-placeholder">Sign output will appear here...</div></div>',
  '      </div>',
  '      <div class="card">',
  '        <div class="card-label">Recent Signs</div>',
  '        <div class="history-list" id="historyList"><div class="history-empty">No signs detected yet</div></div>',
  '      </div>',
  '      <button class="mode-tab" onclick="toggleMode()">Switch to Voice Mode (Mode B)</button>',
  '    </div>',
  '  </div>',
  '  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands.js"></script>',
  '  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js"></script>',
  '  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js"></script>',
  '  <script>',
  '    const BACKEND = "__BACKEND_URL__";',
  '    const texts = {',
  '      en: {',
  '        outputLabel: "Detected Sign",',
  '        start: "Start Signing",',
  '        stop: "Stop Signing",',
  '        placeholder: "Sign output will appear here...",',
  '        historyEmpty: "No signs detected yet",',
  '        accuracy: "Confidence",',
  '        speak: "Speak Again",',
  '        modeButton: "Switch to Voice Mode (Mode B)"',
  '      },',
  '      hi: {',
  '        outputLabel: "Pehchana gaya sanket",',
  '        start: "Sign karein",',
  '        stop: "Rokein",',
  '        placeholder: "Sign ka anuvaad yahan dikhega...",',
  '        historyEmpty: "Abhi koi sanket nahin",',
  '        accuracy: "Vishwasneeyata",',
  '        speak: "Dubara bolen",',
  '        modeButton: "Voice Mode (Mode B) par jayen"',
  '      }',
  '    };',
  '    const signToHindi = { "I need help": "Mujhe madad chahiye", "Call doctor": "Doctor ko bulaiye", "I am in pain": "Mujhe dard hai", "Thank you": "Dhanyavaad", "I am deaf": "Main bahra hoon", "Call police": "Police ko bulaiye", "Water please": "Paani dijiye", "Emergency": "Aapatkal", "I am lost": "Main kho gaya hoon", "I am hungry": "Mujhe bhookh lagi hai" };',
  '    let detecting = false;',
  '    let currentLang = "en";',
  '    let isDark = true;',
  '    let lastSend = 0;',
  '    let history = [];',
  '    let currentResult = null;',
  '    let hands = null;',
  '    let camera = null;',
  '    const video = document.getElementById("video");',
  '    const canvas = document.getElementById("canvas");',
  '    const ctx = canvas.getContext("2d");',
  '    function uiText(key) { return texts[currentLang][key] || texts.en[key] || ""; }',
  '    function translatedSign(sign) { return currentLang === "hi" ? (signToHindi[sign] || sign) : sign; }',
  '    function setStatus(id, color, text) { document.getElementById(id + "Dot").style.background = color; document.getElementById(id + "Status").textContent = text; }',
  '    function updateIdleUI() {',
  '      document.getElementById("outputLabel").textContent = uiText("outputLabel");',
  '      document.getElementById("startBtn").textContent = detecting ? uiText("stop") : uiText("start");',
  '      document.querySelector(".mode-tab").textContent = uiText("modeButton");',
  '      if (!currentResult) { document.getElementById("outputArea").innerHTML = "<div class=\\"output-placeholder\\">" + uiText("placeholder") + "</div>"; }',
  '      if (!history.length) { document.getElementById("historyList").innerHTML = "<div class=\\"history-empty\\">" + uiText("historyEmpty") + "</div>"; }',
  '    }',
  '    function setLang(lang) { currentLang = lang; document.getElementById("btnEN").classList.toggle("active", lang === "en"); document.getElementById("btnHI").classList.toggle("active", lang === "hi"); updateIdleUI(); if (currentResult) { showResult(currentResult); } else if (history.length) { renderHistory(); } }',
  '    function renderHistory() {',
  '      const list = document.getElementById("historyList");',
  '      if (!history.length) { list.innerHTML = "<div class=\\"history-empty\\">" + uiText("historyEmpty") + "</div>"; return; }',
  '      list.innerHTML = history.map(function(item) {',
  '        const label = currentLang === "hi" ? item.hindi : item.sign;',
  '        return "<div class=\\"history-item\\"><div><span class=\\"history-sign\\">" + label + "</span><span style=\\"color:var(--muted);font-size:10px;margin-left:8px\\">" + item.time + "</span></div><span class=\\"history-conf\\">" + item.conf + "%</span></div>";',
  '      }).join("");',
  '    }',
  '    function addToHistory(sign, conf, hindi) { history.unshift({ sign: sign, conf: conf, hindi: hindi, time: new Date().toLocaleTimeString() }); if (history.length > 10) history.pop(); renderHistory(); }',
  '    function speak(text) { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = currentLang === "hi" ? "hi-IN" : "en-US"; utterance.rate = 0.9; window.speechSynthesis.speak(utterance); }',
  '    function showResult(data) {',
  '      currentResult = data;',
  '      const sign = data.sign;',
  '      const conf = data.confidence;',
  '      const hindi = signToHindi[sign] || sign;',
  '      const display = translatedSign(sign);',
  '      document.getElementById("outputArea").innerHTML = "<div class=\\"output-sign\\">" + display + "</div>" + (currentLang === "hi" ? "<div class=\\"output-hindi\\">" + sign + "</div>" : "") + "<div class=\\"output-meta\\"><span class=\\"meta-badge\\">" + uiText("accuracy") + ": " + conf + "%</span><span class=\\"meta-badge\\">" + (data.mode === "model" ? "AI" : "Demo") + "</span></div><button class=\\"btn-speak\\" onclick=\\"speak(" + JSON.stringify(display) + ")\\">" + uiText("speak") + "</button>";',
  '      document.getElementById("signOverlay").style.display = "flex";',
  '      document.getElementById("overlaySign").textContent = display;',
  '      document.getElementById("overlayConf").textContent = conf + "%";',
  '      document.getElementById("outputCard").style.borderColor = "var(--accent)";',
  '      if (conf > 75) { speak(display); }',
  '      addToHistory(sign, conf, hindi);',
  '    }',
  '    async function sendToBackend(landmarks) {',
  '      if (!BACKEND) { return; }',
  '      try {',
  '        const res = await fetch(BACKEND + "/predict", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ landmarks: landmarks }) });',
  '        const data = await res.json();',
  '        showResult(data);',
  '      } catch (error) {',
  '        console.log("Backend error:", error);',
  '      }',
  '    }',
  '    function onResults(results) {',
  '      ctx.clearRect(0, 0, canvas.width, canvas.height);',
  '      if (results.multiHandLandmarks && results.multiHandLandmarks.length > 0) {',
  '        const landmarks = results.multiHandLandmarks[0];',
  '        drawConnectors(ctx, landmarks, HAND_CONNECTIONS, { color: "#00F5D440", lineWidth: 2 });',
  '        drawLandmarks(ctx, landmarks, { color: "#00F5D4", lineWidth: 1, radius: 3 });',
  '        if (detecting) {',
  '          const now = Date.now();',
  '          if (now - lastSend > 800) { lastSend = now; sendToBackend(landmarks.flatMap(function(lm) { return [lm.x, lm.y, lm.z]; })); }',
  '        }',
  '        document.getElementById("cameraStatus").textContent = "Hand detected";',
  '      } else {',
  '        document.getElementById("cameraStatus").textContent = detecting ? "Show your hand clearly" : "Position your hand";',
  '      }',
  '    }',
  '    async function initMediaPipe() {',
  '      try {',
  '        hands = new Hands({ locateFile: function(file) { return "https://cdn.jsdelivr.net/npm/@mediapipe/hands/" + file; } });',
  '        hands.setOptions({ maxNumHands: 1, modelComplexity: 1, minDetectionConfidence: 0.7, minTrackingConfidence: 0.5 });',
  '        hands.onResults(onResults);',
  '        const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user", width: 640, height: 480 } });',
  '        video.srcObject = stream;',
  '        camera = new Camera(video, { onFrame: async function() { canvas.width = video.videoWidth; canvas.height = video.videoHeight; await hands.send({ image: video }); }, width: 640, height: 480 });',
  '        camera.start();',
  '        setStatus("cam", "#00F5D4", "Camera: Active");',
  '        setStatus("mp", "#00F5D4", "MediaPipe: Ready");',
  '        document.getElementById("cameraStatus").textContent = "Camera active - show your hand";',
  '      } catch (error) {',
  '        setStatus("cam", "var(--danger)", "Camera: " + error.message);',
  '        document.getElementById("cameraStatus").textContent = "Camera error: " + error.message;',
  '      }',
  '    }',
  '    async function checkBackend() {',
  '      if (!BACKEND) { setStatus("ai", "var(--danger)", "AI Model: Backend URL missing"); return; }',
  '      try {',
  '        const res = await fetch(BACKEND + "/health");',
  '        const data = await res.json();',
  '        const ok = data.model === "loaded";',
  '        setStatus("ai", ok ? "#00F5D4" : "var(--warn)", ok ? "AI Model: Ready (" + data.signs_count + " signs)" : "AI Model: Not loaded");',
  '      } catch (error) {',
  '        setStatus("ai", "var(--danger)", "AI Model: Backend offline");',
  '      }',
  '    }',
  '    function toggleDetection() { detecting = !detecting; document.getElementById("startBtn").classList.toggle("active", detecting); document.getElementById("startBtn").textContent = detecting ? uiText("stop") : uiText("start"); document.getElementById("cameraStatus").textContent = detecting ? "Detecting signs..." : "Detection paused"; }',
  '    function clearAll() { detecting = false; currentResult = null; history = []; document.getElementById("startBtn").classList.remove("active"); document.getElementById("signOverlay").style.display = "none"; document.getElementById("outputCard").style.borderColor = "var(--border)"; updateIdleUI(); }',
  '    function toggleMode() { alert("Mode B (Voice to Text) is available in the app tabs."); }',
  '    function toggleTheme() { isDark = !isDark; document.body.classList.toggle("light", !isDark); document.getElementById("themeBtn").textContent = isDark ? "Light" : "Dark"; }',
  '    updateIdleUI();',
  '    checkBackend();',
  '    initMediaPipe();',
  '    setInterval(checkBackend, 10000);',
  '  </script>',
  '</body>',
  '</html>',
].join("\\n");
